@server=http://localhost
@port=5293
@host={{server}}:{{port}}
@contentType=application/json

### Get all projects
GET {{host}}/api/Project HTTP/1.1

### Get all projects
GET {{host}}/api/Project/1 HTTP/1.1

### Create a project
POST {{host}}/api/Project HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Project 75",
  "status": "Active",
  "tasks": [],
  "tags": []
}

### Get all Tasks
GET {{host}}/api/Task HTTP/1.1

### Get Task by ID
GET {{host}}/api/Task/1004 HTTP/1.1

### Create a Task
POST {{host}}/api/Task HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Task 36",
  "deadline": "2025-01-29T20:17:49.871Z",
  "projectId": 1
}

### Delete Task by ID
DELETE {{host}}/api/Task/1003 HTTP/1.1

### Add tags to a task /api/Task/{taskId}
POST {{host}}/api/Task/Tags/7 HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Tag 1"
}

### Get all Tags
GET {{host}}/api/Tag HTTP/1.1